version: '3.7'

services:
  dist:
    container_name: locker_services
    restart: always
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug
    ports:
      - ${API_PORT}:${API_PORT}
      - 3001:3001
    networks:
      - locker_network
    env_file:
      - .env
    depends_on:
      - mariadb

  phpmyadmin:
    container_name: ua_phpmyadmin
    image: phpmyadmin:5.2.0
    environment:
      PMA_HOST: mariadb
      PMA_PORT: ${TYPEORM_PORT}
    networks:
      - locker_network
    ports:
      - 3002:80
    depends_on:
      - mariadb

  mariadb:
    container_name: ua_mariadb
    image: mariadb:10.10.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_pass
      MARIADB_USER: ${TYPEORM_USERNAME}
      MARIADB_PASSWORD: ${TYPEORM_PASSWORD}
      MARIADB_DATABASE: ${TYPEORM_DATABASE}
    networks:
      - locker_network
    volumes:
      - mariadb_data:/var/lib/mariadb

volumes:
  mariadb_data:

networks:
  locker_network:
